### ISSUE TITLE
Continue integration of the Search Web Component

### ISSUE THREAD

**Issue by ia3andy** [ia3andy/aloha#107]
https://github.com/ia3andy/tasks/issues/96#issuecomment-1881101418

**Comment by ia3andy** [comment]
As January (Release of Quarkus 3.7) I will focus on having everything ready for the Quarkus Web story, I would prefer to reschedule this task to February (as it not blocked thanks to the current implementation).

@yrodiere Are you ok with this plan?

**Comment by yrodiere** [comment]
Hey @ia3andy , sure. We'll go ahead with the Vue app for now.
