### ISSUE TITLE
Implement a fullstack web-component using Lit for search.quarkus.io

### ISSUE THREAD

**Issue by ia3andy** [ia3andy/aloha#96]
I was pinged on a PR to enhance the  search experience on quarkus.io. This was using Vue and I thought it would not have been easy to maintain on the long term. 

This is why I suggested using the web-bundler and make it a Full-stack Web Component instead. This would be a good show-case for this use-case and would make this tool easier to maintain.. Win Win. 

It took quite some time to implement as there are big constraints (fallbacks) due to infrastructure restriction in the community. 

The web-component is implemented https://github.com/quarkusio/search.quarkus.io/pull/58

Missing pieces to make it available in production:
- [ ] add local search fallback
- [ ] quarkus.io integration

**Comment by yrodiere** [comment]
Thanks for staying on top of this.

A couple things to add:

1. Add copyright mentions for the various assets copied to the search.quarkus.io repository.
   See https://github.com/quarkusio/search.quarkus.io/pull/58#issuecomment-1824708903 :
   > For the icons copyright, I've used the one from quarkusio so we should mimic what they are doing?
2. Search should only get triggered when a minimum number of chars is entered OR a category is selected ; it's already implemented in the existing Vue application, see the request [here](https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/search.2Equarkus.2Eio/near/409130521) and the code [here](https://github.com/quarkusio/quarkusio.github.io/pull/1825/files#diff-6422374ca65d9bea7eac0104b5aa2c6cb7efcee92efbac61156f6c0f6e81ac2eR80-R85) and [there](https://github.com/quarkusio/quarkusio.github.io/pull/1825/files#diff-6422374ca65d9bea7eac0104b5aa2c6cb7efcee92efbac61156f6c0f6e81ac2eR186-R188).
3. The abort logic needs some work, see https://github.com/quarkusio/search.quarkus.io/pull/58#discussion_r1401633018
 and how it can be implemented [here](https://github.com/quarkusio/quarkusio.github.io/pull/1825/files#diff-6422374ca65d9bea7eac0104b5aa2c6cb7efcee92efbac61156f6c0f6e81ac2eR184)
